name: Blueslike


on:
    workflow_dispatch:
    workflow_run:
      workflows: ["Bluesclima"]
      types:
        - completed

jobs:
  run-bot:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.9'

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install requests atproto

      - name: Restore interactions file
        uses: actions/download-artifact@v4
        with:
          name: interactions
          path: .

      - name: Run bot
        env:
          BSKY_HANDLE: ${{ secrets.BSKY_HANDLE }}
          BSKY_PASSWORD: ${{ secrets.BSKY_PASSWORD }}
        run: python blueslike.py

      - name: Save interactions file
        uses: actions/upload-artifact@v4
        with:
          name: interactions
          path: interactions.json
