name: Botoronga


on:
  workflow_run:
    workflows: ["Testovid"]
    types:
      - completed

jobs:

    build:

        runs-on: ubuntu-latest


        steps:

            - uses: actions/checkout@v2

            - name: Make envfile

              uses: SpicyPizza/create-envfile@v1

              with:

                  envkey_CONSUMER_KEY: ${{ secrets.CONSUMER_KEY }}

                  envkey_CONSUMER_SECRET: ${{ secrets.CONSUMER_SECRET }}

                  envkey_ACCESS_TOKEN: ${{ secrets.ACCESS_TOKEN }}

                  envkey_ACCESS_TOKEN_SECRET: ${{ secrets.ACCESS_TOKEN_SECRET }}
                  
                  file_name: .env


            - name: Build the docker container

              run: docker build .


            - name: Run the script 🚀

              run: docker-compose up
