name: Covidson


on: push

#    schedule:

#        - cron: '0 11 * * *'


jobs:

    build:

        runs-on: ubuntu-latest


        steps:

            - name: Check the repo for changes
              uses: actions/checkout@v2
              with:
                fetch-depth: 0
                ref: ${{ github.event.pull_request.head.ref }}

            - name: Keep this repo alive
              uses: gautamkrishnar/keepalive-workflow@master

            - name: Setup python and run
              uses: actions/setup-python@v4
              with:
                    python-version: '3.7'
                    cache: 'pip'
            - run: pip install -r requirements.txt
            - run: python covidson.py
            


            - name: Commit and push

              run: |
                git config --global user.email "github-actions[bot]@users.noreply.github.com"
                git config --global user.name "github-actions[bot]"
                git diff-index --quiet HEAD || (git commit -a -m'[bot] update files' --allow-empty && git push -f)
