name: Covidson


on: push
#    schedule:
 #       - cron: '0 10 * * *'

jobs:
  graphs:
    runs-on: ubuntu-latest

    steps:
      - name: Git checkout code
        uses: actions/checkout@v2
        with:
            fetch-depth: 0
            ref: ${{ github.event.pull_request.head.ref }}
      - name: Setup python and run
        uses: actions/setup-python@v4
        with:
           python-version: '3.7'
           cache: 'pip'
      - run: pip install -r requirements.txt
      - run: python data/covidson.py

      - name: Commit and push
        run: |-
          cd ./data
          git config user.name "Rilufi"
          git config user.email "actions@users.noreply.github.com"
          git add -A
          timestamp=$(date -u)
          git commit -m "Updating graphs: ${timestamp}" || exit 0
          git push
