name: Covidson


on: push

#    schedule:

#        - cron: '0 11 * * *'


jobs:

    build:

        runs-on: ubuntu-latest


        steps:

            - uses: actions/checkout@v2
            
            - uses: gautamkrishnar/keepalive-workflow@master

            - name: Run the script 🚀

              run: python3 /code/covidson.py
            
            - name: Commit the changes
            
              uses: stefanzweifel/git-auto-commit-action@v4
