name: Testovid


#on: push

  #  schedule:

      #  - cron: '0 10 * * *'

jobs:

    build:

        runs-on: ubuntu-latest

        steps:

            - name: Check the repo for changes
              uses: actions/checkout@v2
              with:
                fetch-depth: 0
                ref: ${{ github.event.pull_request.head.ref }}
            - name: Checkout game state
              uses: actions/checkout@v2
              with:
                ref: save
            - name: Setup python and run
              uses: actions/setup-python@v4
              with:
                    python-version: '3.7'
                    cache: 'pip'
            - run: pip install -r requirements.txt
            - run: python covidson.py
            
            - name: Commit the changes
              uses: stefanzweifel/git-auto-commit-action@v4
