name: Testovid

on: push
 # workflow_dispatch:
 # schedule:
 #   - cron: "*/5 * * * *"

jobs:
  tweet:
    runs-on: ubuntu-latest

    steps:
      - name: Git checkout code
        uses: actions/checkout@v2
      - name: Checkout graphs state
        uses: actions/checkout@v2
        with:
          ref: main
          path: data
      - name: Setup python and run
        uses: actions/setup-python@v4
        with:
           python-version: '3.7'
           cache: 'pip'
      - run: pip install -r requirements.txt
      - run: python covidson.py

      - name: Commit and push
        run: |-
          cd ./data
          git config user.name "Rilufi"
          git config user.email "actions@users.noreply.github.com"
          git add -A
          timestamp=$(date -u)
          git commit -m "Latest data: ${timestamp}" || exit 0
          git push
